name: fairlearn-pycon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - markupsafe==2.0.1
  - fairlearn==0.7.0
  - jupyter
  - seaborn>=0.11
  - scikit-learn>=1.0.0
  - pip:
      - model-card-toolkit>=1.0.0